apiVersion: v1
kind: Pod
metadata:
  name: app-multicontainer
spec:
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: shared-volume
      mountPath: /data
    command: ["/bin/sh", "-c"]
    args: ["while true; do date >> /data/datetime.txt; sleep 1; done"]
  volumes:
  - name: shared-volume
    emptyDir: {}
