apiVersion: v1
kind: Pod
metadata:
  name: app-readinessProbe
spec:
  containers:
  - name: mycontainer
    image: gcr.io/k8s-k3s/demo:v2.0.0
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /
        port: 8000
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
