apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: mycontainer
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    volumeMounts:
    - name: app-volume-mount
      mountPath: /data
  volumes:
  - name: app-volume-mount
    hostPath:
      path: /var/lib/app
