apiVersion: v1
kind: Pod
metadata:
  name: app-livenessProbe
spec:
  containers:
  - name: mycontainer
    image: gcr.io/k8s-k3s/demo:v1.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8000
