apiVersion: v1
kind: Pod
metadata:
  name: app-resources
spec:
  containers:
  - name: mycontainer
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
